### ISSUE TITLE
Event-Extraction

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/Relationships#10]
Extract events from the text

**Comment by ansjin** [comment]
@Sandr00  I think we can close this. Its already done!

**Comment by Sandr0x00** [comment]
Currently, only working algorithm working on Azure. Are saved to DB (currently local).

**Comment by kordianbruck** [comment]
@Sandr00 that sentence makes no sense in the manner of English grammar. Can you please rephrase and explain what you it is that you want to tell the world?

**Comment by ansjin** [comment]
@kordianbruck Actually that means we are able to run, extract and save events to DB by using Event Extraction algorithm on the large amount of data (given by team-2).

The problem with other algorithms is that the data which we are sending to them is mix of Unicode characters which sometimes those algorithms are not able  to process and gets crashed. But we modified the algorithms so now this is not a problem.

The other problem is the data size limit the other algorithms can process. Sometimes if we pass huge amount of data to them, they gets crashed.  We are currently modifying the algos to resolve this issue!

**Comment by Sandr0x00** [comment]
@kordianbruck yes you are right, shame on me.
@ansjin Thanks for explaining.

At the time I closed this Issue, this algorithm was the only one, which was fully functioning (we are able to call it with large amounts of data and it does not crash) and running on Azure.
Current state: Anshul already modified more algorithms.
