### ISSUE TITLE
Algorithm calls

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/Relationships#11]
- [x] call Coref #43 
- [x] replace text with Corefs
- [x] call OpenIE (Washington) #42 
- [x] call OpenIE (Stanford) #45 
- [x] call Ollie #41 
- [x] call DateExtraction #39

**Comment by Henni** [comment]
@ansjin what's the current state on this?

**Comment by ansjin** [comment]
Tick marked in the issue! Also calling Event Extraction Algo is done!

I want to first test the complete chain with one Ollie algorithm

DBRead->WETParse 
-> Coreference Resolution -> Ollie- > Results Saved in Db
-> Event Extraction -> Results Saved in Db

once its working fine then those changes can be done for (openIE(both), Exemplar).

**Comment by Sandr0x00** [comment]
Finished with #48

**Comment by ansjin** [comment]
https://github.com/MusicConnectionMachine/Relationships/pull/48
