### ISSUE TITLE
Write Data to DB

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/Relationships#16]
Right after we ran the relationship-extraction algorithms we want to write our results to the database.
Additionally we want to write our classification results to the database.

TODOs:
- [x] write raw data
- [x] write classification attributes

**Comment by Sandr0x00** [comment]
At the moment we write the raw data with some stemming.
Classifying not yet done, so we can't write classified data, maybe we should add the writing of classified data to the classify issue?

**Comment by simonzachau** [comment]
As described in the [classification issue](https://github.com/MusicConnectionMachine/Relationships/issues/9#issuecomment-293906123) this is done. The only thing missing is the knowledge of the direction of a relation, which is not relevant in this issue.
