### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/Relationships#22]
go over to codeacy and fix *all* the issues.

**Comment by kordianbruck** [comment]
![fca8c0f713092a47588cdf8a83974725_dev-new-discussion-on-bug-fix-meme_554-369](https://cloud.githubusercontent.com/assets/298860/24684362/add14be2-19a5-11e7-8151-e7faf46fa26e.jpeg)

# Please don't spend too much time on this. This is not a priority at all. Like no. Please don't.

**Comment by Henni** [comment]
@kordianbruck :+1: thus low-priority and milestone for beta-release

**Comment by kordianbruck** [comment]
So as we are nearing release, I'm not sure we got time for this as there are so many other issues open. Lets close this and we can revisit the idea some day.
