### ISSUE TITLE
Data for Relations

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/Relationships#46]
Hi guys,

as the things are calming down I assume the data is figured out - how / where can I access relations data? Is there an api for that or is it only in a database?

Thanks

PS. Please set high priority to this task as we need it asap.

**Comment by simonzachau** [comment]
Yes, there is an API. It runs on Azure on http://musicconnectionapi.azurewebsites.net.
Currently, there are no relations accessible though. We're working on getting some up there.

**Comment by lustoykov** [comment]
Thanks for the response.

Where can I read documentation? (endpoints + what they deliver)

**Comment by lustoykov** [comment]
Thanks for the response! Please let me know when it is ready 👍

**Comment by simonzachau** [comment]
The endpoints are defined in the [swagger](https://github.com/MusicConnectionMachine/api/tree/develop/api/swagger/src/paths/relationships)

**Comment by kordianbruck** [comment]
Update on this? Done?

**Comment by simonzachau** [comment]
@kordianbruck @lustoykov as I wrote before, I think all parts that are already integrated and the ones that are still due are nicely listed in the API repo. This issue should have been in the API from the start. Therefore, I close it now.
