### ISSUE TITLE
Read "complete" stop word list

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/Relationships#60]
see https://github.com/MusicConnectionMachine/Relationships/pull/58#discussion_r111369473

**Comment by sacdallago** [comment]
I guess importing this from its `.csv` from somewhere wouldn't be that bad.

**Comment by kordianbruck** [comment]
Or have a simple txt file that has one word per line. Does not matter really.

**Comment by sacdallago** [comment]
Update. We can create the list [here](https://github.com/MusicConnectionMachine/dictionaries) and read it in as a cli parameter, OK? So you @Henni / @MusicConnectionMachine/group-3 & @MusicConnectionMachine/group-4 can worry about defining an initial list, and this will then be curated with patience by the crowd

**edit**: you can really go as far as using the web interface of GH to "create new file" and dump in all words you have right now :) Then at the bottom you get the option of "commit on a new branch and open PR". For later modifications, you can directly edit via web interface and open PRs :) I think it's a good solution but then again I came up with it so I'm not very impartial :D :D :D 

**edit 2**: [ups](https://github.com/MusicConnectionMachine/dictionaries/blob/master/stop_words)

**Comment by Sandr0x00** [comment]
Done in #67
