### ISSUE TITLE
Very Important Fixes that should be done tomorrow

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/Relationships#72]
We have to fix the following: 
- [x] `relationships` is empty, no idea why ... 😟 
- [x] `relationshipTypes` and `relationshipDescriptions` are duplicated because it get's inserted everytime we start the process; @simonzachau working on this
- [x] still no matching in `events`, @ansjin is on that, Fixed  @https://github.com/MusicConnectionMachine/Relationships/pull/76
- [x] API-Stuff for G5/6, maybe there is an issue in the api @Henni ?

**Comment by kordianbruck** [comment]
Yes, there are separate issues for G5/6

**Comment by simonzachau** [comment]
update regarding `relationships is empty`:
![screen shot 2017-04-23 at 12 57 59](https://cloud.githubusercontent.com/assets/9423641/25312931/26047d18-2825-11e7-9033-2ea8d3e4be4a.png)
@ansjin said he's looking into it

**Comment by simonzachau** [comment]
As @ansjin told me, the `relationships` table is also working again now, so this issue can be closed.
